### PR TITLE
Update static submodule after pulling in lastest changes

### PR DESCRIPTION
**Pull request by ivanistheone**
This pulls in quite a bit of commits in https://github.com/sympy/sympy-web-static/

@asmeurer can you review diff to make sure not changes won't break anything?

Commands I used were as per your suggestion:

```
cd static 
git checkout master
git pull
cd ..
git add static
git commit
```

### CODE REVIEW

**Comment by asmeurer** [comment]
Looks like it hasn't been updated in a while. I think everything else that has changed is specific to live, so it shouldn't affect things. I'm inclined to just merge this and see if it works.

**Comment by asmeurer** [comment]
And as I mentioned on the other PR, we should remote the submodule and just copy the files directly to this repo, since we plan on sunsetting the sympy-live repo. We can also remove any static files that are only used on live (like all the Live specific Javascript).

**Comment by ivanistheone** [comment]
It seems that travis didn't run after this was merged:
https://github.com/sympy/sympy.github.com/commits/gh-pages

Not sure if you have access to travis logs and could see what might have gone wrong.

**Comment by asmeurer** [comment]
Travis did run but no changes were made since the commit to gh-pages so nothing was pushed.

**Comment by asmeurer** [comment]
It appears to have cloned commit 17705d2cf89620564a3d0b99601219870ee7dc45 of the static repo. Not sure why there wouldn't be any changes.

**Comment by asmeurer** [comment]
https://travis-ci.org/github/sympy/sympy.github.com/builds/774803558

**Comment by asmeurer** [comment]
Looks like static is also a submodule on the `gh-pages` branch. So to update the site, we would need to update it there too.

**Comment by asmeurer** [comment]
I updated the static submodule on `gh-pages`. When we remove the submodule from sources we need to remember to remove it from gh-pages too so that it just gets deployed normally.

**Comment by ivanistheone** [comment]
Nice. Confirm new menu js is deployed https://www.sympy.org/en/index.html and seems to be working

**Comment by asmeurer** [comment]
I still see the issue on mobile safari if I don't disable my content blockers. We obviously don't need to support content blockers, but I find it odd that one of the ad blockers I had installed is blocking our custom Javascript.

**Pull request merged**
