### PR TITLE
Add link to Introduction to contributing in quick links

### PR DESCRIPTION
**Pull request by debugger22**
Add link to Introduction to contributing in quick links and also change http to https wherever required.

### CODE REVIEW

**Comment by debugger22** [comment]
@asmeurer Please see this.

**Comment by jcrist** [comment]
+1

**Comment by certik** [comment]
The change is good, but you need to modify this file: https://github.com/sympy/sympy.github.com/blob/b37a1cfe7e59bb3be7d0d59c3bd9e1f532ec44c9/templates/base.html#L67

**Comment by debugger22** [comment]
I have `Babel` installed but it didn't translate `Introduction to contributing` to respective languages while executing `./generate`.

**Comment by debugger22** [comment]
@certik ping.

**Comment by debugger22** [comment]
@asmeurer @certik It would be a good time to merge this PR.

**Comment by debugger22** [comment]
​Thanks!​

Sudhanshu Mishra

**Pull request merged**
