### PR TITLE
Add GitHub Actions to build and deploy

### PR DESCRIPTION
**Pull request by aktech**
- [x] add relative static paths
- [x] Make copyright year dynamic
- [x] Misc fixes and formatting.

Working Link (on my fork): http://iamit.in/sympy.github.com

### CODE REVIEW

**Comment by aktech** [comment]
ping @asmeurer

**Comment by aktech** [comment]
ping +=1 @asmeurer

**Comment by asmeurer** [comment]
Never noticed this, sorry. I guess the only way to tell if it really works is to merge it.

**Comment by asmeurer** [comment]
Looks like this broke the build. The page content loads but none of the CSS does. I reverted it for now, but you can see the broken build on the gh-pages branch here 45f11d7ba667c1aaecdb3c1e67a40b6ea65d904a

**Comment by asmeurer** [comment]
Also the build seems to put a bunch of stuff in the `build` directory of the gh-pages branch.

**Comment by aktech** [comment]
Sure, let me take a look.

**Comment by asmeurer** [comment]
By the way you should have push access here feel free to push/merge stuff directly here, as long as you check that everything works after you deploy.

**Comment by asmeurer** [comment]
Might be a good idea to temporarily disable the GitHub Actions script for now and only use manual deploys. In the current state, if anyone merges any PR here it will break the website.

**Comment by asmeurer** [comment]
> Might be a good idea to temporarily disable the GitHub Actions script for now and only use manual deploys. In the current state, if anyone merges any PR here it will break the website.

I've done this.

**Pull request merged**
