### PR TITLE
Correct dead link to galgebra

### PR DESCRIPTION
**Pull request by eric-wieser**
https://github.com/pygae/galgebra is the new home

### CODE REVIEW

**Comment by jksuom** [comment]
Thanks.

**Comment by eric-wieser** [comment]
Whoops, this change was made on the wrong branch, cc @oscarbenjamin

**Comment by oscarbenjamin** [comment]
Should it be on the 1.6 branch? I'm about to release 1.6.2...

**Comment by eric-wieser** [comment]
That branch doesn't exist. It should be on "sources" I think

**Pull request merged**
